DOMINOS = [
    (1, {'decor':'FIELD', 'crown':0}, {'decor':'FIELD', 'crown':0}),
    (2, {'decor':'FIELD', 'crown':0}, {'decor':'FIELD', 'crown':0}),
    (3, {'decor':'FOREST', 'crown':0}, {'decor':'FOREST', 'crown':0}),
    (4, {'decor':'FOREST', 'crown':0}, {'decor':'FOREST', 'crown':0}),
    (5, {'decor':'FOREST', 'crown':0}, {'decor':'FOREST', 'crown':0}),
    (6, {'decor':'FOREST', 'crown':0}, {'decor':'FOREST', 'crown':0}),
    (7, {'decor':'LAKE', 'crown':0}, {'decor':'LAKE', 'crown':0}),
    (8, {'decor':'LAKE', 'crown':0}, {'decor':'LAKE', 'crown':0}),
    (9, {'decor':'LAKE', 'crown':0}, {'decor':'LAKE', 'crown':0}),
    (10, {'decor':'MEADOW', 'crown':0}, {'decor':'MEADOW', 'crown':0}),
    (11, {'decor':'MEADOW', 'crown':0}, {'decor':'MEADOW', 'crown':0}),
    (12, {'decor':'SWAMP', 'crown':0}, {'decor':'SWAMP', 'crown':0}),
    (13, {'decor':'FOREST', 'crown':0}, {'decor':'FIELD', 'crown':0}),
    (14, {'decor':'LAKE', 'crown':0}, {'decor':'FIELD', 'crown':0}),
    (15, {'decor':'MEADOW', 'crown':0}, {'decor':'FIELD', 'crown':0}),
    (16, {'decor':'SWAMP', 'crown':0}, {'decor':'MEADOW', 'crown':0}),
    (17, {'decor':'LAKE', 'crown':0}, {'decor':'FOREST', 'crown':0}),
    (18, {'decor':'MEADOW', 'crown':0}, {'decor':'FOREST', 'crown':0}),
    (19, {'decor':'FOREST', 'crown':0}, {'decor':'FIELD', 'crown':1}),
    (20, {'decor':'LAKE', 'crown':0}, {'decor':'FIELD', 'crown':1}),
    (21, {'decor':'MEADOW', 'crown':0}, {'decor':'FIELD', 'crown':1}),
    (22, {'decor':'SWAMP', 'crown':0}, {'decor':'FIELD', 'crown':1}),
    (23, {'decor':'MINE', 'crown':0}, {'decor':'FIELD', 'crown':1}),
    (24, {'decor':'FIELD', 'crown':0}, {'decor':'FOREST', 'crown':1}),
    (25, {'decor':'FIELD', 'crown':0}, {'decor':'FOREST', 'crown':1}),
    (26, {'decor':'FIELD', 'crown':0}, {'decor':'FOREST', 'crown':1}),
    (27, {'decor':'FIELD', 'crown':0}, {'decor':'FOREST', 'crown':1}),
    (28, {'decor':'LAKE', 'crown':0}, {'decor':'FOREST', 'crown':1}),
    (29, {'decor':'MEADOW', 'crown':0}, {'decor':'FOREST', 'crown':1}),
    (30, {'decor':'FIELD', 'crown':0}, {'decor':'LAKE', 'crown':1}),
    (31, {'decor':'FIELD', 'crown':0}, {'decor':'LAKE', 'crown':1}),
    (32, {'decor':'FOREST', 'crown':0}, {'decor':'LAKE', 'crown':1}),
    (33, {'decor':'FOREST', 'crown':0}, {'decor':'LAKE', 'crown':1}),
    (34, {'decor':'FOREST', 'crown':0}, {'decor':'LAKE', 'crown':1}),
    (35, {'decor':'FOREST', 'crown':0}, {'decor':'LAKE', 'crown':1}),
    (36, {'decor':'MEADOW', 'crown':1}, {'decor':'FIELD', 'crown':0}),
    (37, {'decor':'MEADOW', 'crown':1}, {'decor':'LAKE', 'crown':0}),
    (38, {'decor':'SWAMP', 'crown':0}, {'decor':'FIELD', 'crown':1}),
    (39, {'decor':'SWAMP', 'crown':0}, {'decor':'MEADOW', 'crown':0}),
    (40, {'decor':'FIELD', 'crown':0}, {'decor':'MINE', 'crown':1}),
    (41, {'decor':'MEADOW', 'crown':2}, {'decor':'FIELD', 'crown':0}),
    (42, {'decor':'MEADOW', 'crown':2}, {'decor':'LAKE', 'crown':0}),
    (43, {'decor':'SWAMP', 'crown':2}, {'decor':'FIELD', 'crown':0}),
    (44, {'decor':'SWAMP', 'crown':2}, {'decor':'MEADOW', 'crown':0}),
    (45, {'decor':'FIELD', 'crown':0}, {'decor':'MINE', 'crown':2}),
    (46, {'decor':'MINE', 'crown':2}, {'decor':'SWAMP', 'crown':0}),
    (47, {'decor':'MINE', 'crown':2}, {'decor':'SWAMP', 'crown':0}),
    (48, {'decor':'MINE', 'crown':3}, {'decor':'FIELD', 'crown':0})
]

def print_dominos(d):
    for id, nd1, nd2 in d:
        nd1_str = nd1['decor'] if (crown := nd1['crown']) == 0 else f"{crown} * {nd1['decor']}"
        nd2_str = nd2['decor'] if (crown := nd2['crown']) == 0 else f"{crown} * {nd2['decor']}"
        print(f'{id})\t[{nd1_str:^10} | {nd2_str:^10}]')